
describe("Signing in and Signing up", function(){
    it(" clicks on the sign up and it takes you to the /home page", function () {
        cy.task("TruncateUserTable")
        //cy.task("createPeep")
        cy.visit('/')
        cy.get("#signUp").click()
        cy.get("#emailSignUp").type("Regin")
        cy.get("#passwordHashSignUp").type("Maru")
        cy.get("#submitSignUp").click()
        cy.url().should('include','/home')
    })
    it(" clicks on the sign up and it takes you to the /home page", function () {
        // cy.task("TruncateUserTable")
        //cy.task("createPeep")
        cy.visit('/')

        cy.get("#signIn").click()
        cy.get("#emailSignIn").type("Regin")
        cy.get("#passwordHashSignIn").type("Maru")
        cy.get("#submitSignIn").click()
        cy.url().should('include','/home')
    })
    xit(" clicks on the sign up and it takes you to the /home page and shows you all the peeps that you have created", function (){
        cy.task("TruncateUserTable")
        cy.task("CreatePeep")
        cy.visit('/')
        cy.get("#signIn").click()
        cy.get("#signUp").click()
        cy.get("#emailSignUp").type("Regin")
        cy.get("#passwordHashSignUp").type("Maru")
        cy.get("#submitSignUp").click()
        cy.get('#peeps').should('contain', 'not a real message, like in real life. Stop being on your computers and go outside')
    })
    
    it(" logout button works for both sign up and sign in", function () {
        cy.task("TruncateUserTable")
        //cy.task("createPeep")
        cy.visit('/')
        cy.get("#signUp").click()
        cy.get("#emailSignUp").type("Regin")
        cy.get("#passwordHashSignUp").type("Maru")
        cy.get("#submitSignUp").click()
        cy.url().should('include','/home')
        cy.get("#logout").click()
        cy.get("#signIn").click()
        cy.get("#emailSignIn").type("Regin")
        cy.get("#passwordHashSignIn").type("Maru")
        cy.get("#submitSignIn").click()
        cy.url().should('include','/home')
        cy.get("#logout").click()
        cy.url().should("contain", '/')
    })
    
})